/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulatormultifungsipbo;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSains = new javax.swing.JLabel();
        btnSuhu = new javax.swing.JLabel();
        btnBentuk = new javax.swing.JLabel();
        btnBMI = new javax.swing.JLabel();
        btnexit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSains.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSainsMouseClicked(evt);
            }
        });
        getContentPane().add(btnSains, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 800, 60, 60));

        btnSuhu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuhuMouseClicked(evt);
            }
        });
        getContentPane().add(btnSuhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 800, 60, 70));

        btnBentuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBentukMouseClicked(evt);
            }
        });
        getContentPane().add(btnBentuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 800, 70, 60));

        btnBMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBMIMouseClicked(evt);
            }
        });
        getContentPane().add(btnBMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 800, 70, 80));

        btnexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexitMouseClicked(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-calculator-52.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabel6.setText("Kalkulator Multifungsi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel2.setText("Nama Kelompok :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel3.setText("1. Mohammad Nurul Hilal (09020620033)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel4.setText("2. Muhammad Shofiuddin (09020620036)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel5.setText("3. Almar'atus Sholekah (09040620046)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/504 (2).png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSainsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSainsMouseClicked
        // TODO add your handling code here:
        new MenuScientific().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSainsMouseClicked

    private void btnSuhuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuhuMouseClicked
        // TODO add your handling code here:
        new MenuSuhu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSuhuMouseClicked

    private void btnBentukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBentukMouseClicked
        // TODO add your handling code here:
        new MenuBangundatar().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnBentukMouseClicked

    private void btnBMIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBMIMouseClicked
        // TODO add your handling code here:
        new MenuBMI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBMIMouseClicked

    private void btnexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMouseClicked
        // TODO add your handling code here:
        int X= JOptionPane.showConfirmDialog(null,"Keluar Program","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(X==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnexitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnBMI;
    private javax.swing.JLabel btnBentuk;
    private javax.swing.JLabel btnSains;
    private javax.swing.JLabel btnSuhu;
    private javax.swing.JLabel btnexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
