/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulatormultifungsipbo;

import javax.swing.JOptionPane;
import sc.BMI;

/**
 *
 * @author user
 */
public class MenuBMI extends javax.swing.JFrame {
    
    void hitung() {
        BMI bmi = new BMI();
        float tinggi,berat,hasil;
         tinggi = Float.parseFloat(txtinggi.getText());
         tinggi = tinggi/100;
         berat = Float.parseFloat(txtberat.getText());
         bmi.setTinggi(tinggi);
         bmi.setBerat(berat);
         bmi.setHasil();
         hasil = bmi.getHasil();
         txthasil.setText(Float.toString(hasil));
         if (hasil<18.5){
            txtket.setText("Kurus");
        }else if (hasil<=22.9){
            txtket.setText("Normal");
        }else if (hasil<24.9){
            txtket.setText("Overweight");
        }else {
            txtket.setText("Obesitas");    
        }
         float tinggiB= tinggi*100;
         if(genderCb.getSelectedIndex() == 1){
                double bbIdeal;
                bbIdeal=((tinggiB-100)-((tinggiB-100))*0.10);
                info.setText("Berat badan ideal anda adalah");
                info2.setText(bbIdeal+" kg");
        } else {
            double bbIdeal;
            bbIdeal=((tinggiB-100)-(0.15*(tinggiB-100)));
                info.setText("Berat badan ideal anda adalah");
                info2.setText(bbIdeal+" kg");
        }

    }

    /**
     * Creates new form MenuBMI
     */
    public MenuBMI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBentuk = new javax.swing.JLabel();
        btnSuhu = new javax.swing.JLabel();
        btnSains = new javax.swing.JLabel();
        btnBMI = new javax.swing.JLabel();
        btnexit = new javax.swing.JLabel();
        mnbmi = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtberat = new javax.swing.JTextField();
        txtinggi = new javax.swing.JTextField();
        txthasil = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        txtket = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        genderCb = new javax.swing.JComboBox<>();
        info = new javax.swing.JLabel();
        info2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBentuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBentukMouseClicked(evt);
            }
        });
        getContentPane().add(btnBentuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 800, 70, 60));

        btnSuhu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuhuMouseClicked(evt);
            }
        });
        getContentPane().add(btnSuhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 800, 60, 70));

        btnSains.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSainsMouseClicked(evt);
            }
        });
        getContentPane().add(btnSains, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 800, 70, 80));

        btnBMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBMIMouseClicked(evt);
            }
        });
        getContentPane().add(btnBMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 810, 60, 70));

        btnexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexitMouseClicked(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 60, 50));

        mnbmi.setBackground(new java.awt.Color(245, 245, 245));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel10.setText("Berat Badan");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel11.setText("Tinggi");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel13.setText("Hasil");

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel14.setText("Keterangan");

        txtberat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtberat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtberatActionPerformed(evt);
            }
        });

        txtinggi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinggiActionPerformed(evt);
            }
        });

        txthasil.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txthasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthasilActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        txtket.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtketActionPerformed(evt);
            }
        });

        jLabel4.setText("Jenis Kelamin");

        genderCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Jenis Kelamin--", "Laki-laki", "Perempuan" }));

        javax.swing.GroupLayout mnbmiLayout = new javax.swing.GroupLayout(mnbmi);
        mnbmi.setLayout(mnbmiLayout);
        mnbmiLayout.setHorizontalGroup(
            mnbmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnbmiLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(mnbmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(mnbmiLayout.createSequentialGroup()
                        .addGroup(mnbmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mnbmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGroup(mnbmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mnbmiLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(mnbmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mnbmiLayout.createSequentialGroup()
                                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtket, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mnbmiLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(mnbmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(genderCb, 0, 189, Short.MAX_VALUE)
                                    .addComponent(txtberat)
                                    .addComponent(txtinggi)))))
                    .addGroup(mnbmiLayout.createSequentialGroup()
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(info2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        mnbmiLayout.setVerticalGroup(
            mnbmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnbmiLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(mnbmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtberat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(31, 31, 31)
                .addGroup(mnbmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(mnbmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(genderCb, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(mnbmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(mnbmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txthasil, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(mnbmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtket, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel14))
                .addGap(27, 27, 27)
                .addGroup(mnbmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(mnbmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 410, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/4.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBentukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBentukMouseClicked
        // TODO add your handling code here:
        new MenuBangundatar().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnBentukMouseClicked

    private void btnSuhuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuhuMouseClicked
        // TODO add your handling code here:
        new MenuSuhu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSuhuMouseClicked

    private void btnSainsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSainsMouseClicked
        // TODO add your handling code here:
        new MenuScientific().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSainsMouseClicked

    private void btnBMIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBMIMouseClicked
        // TODO add your handling code here:
        new MenuBMI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBMIMouseClicked

    private void btnexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMouseClicked
        // TODO add your handling code here:
        int X= JOptionPane.showConfirmDialog(null,"Keluar Program","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(X==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnexitMouseClicked

    private void txtberatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtberatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtberatActionPerformed

    private void txtinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinggiActionPerformed

    private void txthasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthasilActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        hitung();
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        genderCb.setSelectedItem("--Jenis Kelamin--");
        txtinggi.setText("");
        txtberat.setText("");
        txthasil.setText("");
        txtket.setText("");
        info.setText("");
        info2.setText("");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBMI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnBMI;
    private javax.swing.JLabel btnBentuk;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel btnSains;
    private javax.swing.JLabel btnSuhu;
    private javax.swing.JLabel btnexit;
    private javax.swing.JComboBox<String> genderCb;
    private javax.swing.JLabel info;
    private javax.swing.JLabel info2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel mnbmi;
    private javax.swing.JTextField txtberat;
    private javax.swing.JTextField txthasil;
    private javax.swing.JTextField txtinggi;
    private javax.swing.JTextField txtket;
    // End of variables declaration//GEN-END:variables
}
