/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulatormultifungsipbo;

import javax.swing.JOptionPane;
import sc.Celcius;
import sc.Fahrenheit;
import sc.Kelvin;
import sc.Reamur;
/**
 *
 * @author user
 */
public class MenuSuhu extends javax.swing.JFrame {

    /**
     * Creates new form MenuSuhu
     */
    public MenuSuhu() {
        initComponents();
    }
    
      public void hitung() {
        double suhu, hasil;
        int keSuhu,kesuhu, dariSuhu;
        suhu = Double.valueOf(valuesuhu.getText());
        dariSuhu = 0;
        dariSuhu = pilihsuhu.getSelectedIndex();
        
        keSuhu = 0;
        if(jRadioButton1.isSelected()){
            keSuhu = 1;
        }if(jRadioButton2.isSelected()){
            keSuhu= 2;
        }if(jRadioButton3.isSelected()){
            keSuhu=3;
        }
        hasil = 0;
        Kelvin k = new Kelvin();
        Celcius c = new Celcius();
        Fahrenheit f = new Fahrenheit();
        Reamur r = new Reamur();
        if(dariSuhu == 1){ //Kelvin
            k.setSuhu(suhu);
            k.setSuhu2(keSuhu);
            k.getSuhu();
            k.getSuhu2();
            k.Hitung();
            hasil =k.getHasil();
        }else if(dariSuhu == 2){ //Celcius
            c.setSuhu(suhu);
            c.setSuhu2(keSuhu);
            c.getSuhu();
            c.getSuhu2();
            c.Hitung();
            hasil =c.getHasil();
        }else if(dariSuhu == 3){ //Reamur
            f.setSuhu(suhu);
            f.setSuhu2(keSuhu);
            f.getSuhu();
            f.getSuhu2();
            f.Hitung();
            hasil =f.getHasil();
        }
        else if(dariSuhu == 4){ //Reamur
            r.setSuhu(suhu);
            r.setSuhu2(keSuhu);
            r.getSuhu();
            r.getSuhu2();
            r.Hitung();
            hasil =r.getHasil();
        }
        hasilkonversi.setText(""+hasil);
        }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mnsuhu = new javax.swing.JPanel();
        hasilkonversi = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        valuesuhu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        pilihsuhu = new javax.swing.JComboBox<>();
        btnBMI = new javax.swing.JLabel();
        btnBentuk = new javax.swing.JLabel();
        btnSuhu = new javax.swing.JLabel();
        btnSains = new javax.swing.JLabel();
        btnexit = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mnsuhu.setBackground(new java.awt.Color(245, 245, 245));

        hasilkonversi.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exchange.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });

        jLabel5.setText("Hasil Konversi :");

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);

        buttonGroup1.add(jRadioButton2);

        buttonGroup1.add(jRadioButton1);

        jLabel2.setText("Konversi");

        pilihsuhu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pilihsuhu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Suhu--", "Kelvin", "Celcius", "Fahrenheit", "Reamur" }));
        pilihsuhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihsuhuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mnsuhuLayout = new javax.swing.GroupLayout(mnsuhu);
        mnsuhu.setLayout(mnsuhuLayout);
        mnsuhuLayout.setHorizontalGroup(
            mnsuhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnsuhuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnsuhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mnsuhuLayout.createSequentialGroup()
                        .addGroup(mnsuhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valuesuhu)
                            .addGroup(mnsuhuLayout.createSequentialGroup()
                                .addGroup(mnsuhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jLabel2)
                                    .addComponent(jRadioButton1)
                                    .addComponent(hasilkonversi)
                                    .addComponent(pilihsuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(mnsuhuLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(30, 30, 30))))
            .addGroup(mnsuhuLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mnsuhuLayout.setVerticalGroup(
            mnsuhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnsuhuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pilihsuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addGap(14, 14, 14)
                .addComponent(valuesuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mnsuhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(hasilkonversi)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        getContentPane().add(mnsuhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 470));

        btnBMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBMIMouseClicked(evt);
            }
        });
        getContentPane().add(btnBMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 810, 60, 60));

        btnBentuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBentukMouseClicked(evt);
            }
        });
        getContentPane().add(btnBentuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 800, 70, 60));

        btnSuhu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuhuMouseClicked(evt);
            }
        });
        getContentPane().add(btnSuhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 800, 60, 70));

        btnSains.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSainsMouseClicked(evt);
            }
        });
        getContentPane().add(btnSains, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 800, 60, 70));

        btnexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexitMouseClicked(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 20, 60, 60));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSainsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSainsMouseClicked
        // TODO add your handling code here:
        new MenuScientific().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSainsMouseClicked

    private void btnSuhuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuhuMouseClicked
        // TODO add your handling code here:
        new MenuSuhu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSuhuMouseClicked

    private void btnBentukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBentukMouseClicked
        // TODO add your handling code here:
        new MenuBangundatar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBentukMouseClicked

    private void btnBMIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBMIMouseClicked
        // TODO add your handling code here:
        new MenuBMI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBMIMouseClicked

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        // TODO add your handling code here:
        hitung();
    }//GEN-LAST:event_jLabel12MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pilihsuhu.setSelectedItem("--Pilih Suhu--");
        buttonGroup1.clearSelection();
        valuesuhu.setText("");
        jRadioButton1.setText("");
        jRadioButton2.setText("");
        jRadioButton3.setText("");
        hasilkonversi.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pilihsuhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihsuhuActionPerformed
        if(pilihsuhu.getSelectedIndex() == 1)
        {
            jRadioButton1.setVisible(true);
            jRadioButton2.setVisible(true);
            jRadioButton3.setVisible(true);

            //menambahkan teks pada radio button
            jRadioButton1.setText("Kelvin ke Celcius");
            jRadioButton2.setText("Kelvin ke Fahrenheit");
            jRadioButton3.setText("Kelvin ke Reamur");
        }
        else if(pilihsuhu.getSelectedIndex() == 2)
        {
            jRadioButton1.setVisible(true);
            jRadioButton2.setVisible(true);
            jRadioButton3.setVisible(true);

            //menambahkan teks pada radio button
            jRadioButton1.setText("Celcius ke Kelvin");
            jRadioButton2.setText("Celcius ke Fahrenheit");
            jRadioButton3.setText("Celcius ke Reamur");
        }
        else if(pilihsuhu.getSelectedIndex() == 3)
        {
            jRadioButton1.setVisible(true);
            jRadioButton2.setVisible(true);
            jRadioButton3.setVisible(true);

            //menambahkan teks pada radio button
            jRadioButton1.setText("Fahrenheit ke Kelvin");
            jRadioButton2.setText("Fahrenheit ke Celcius");
            jRadioButton3.setText("Fahrenheit ke Reamur");
        }
        else if(pilihsuhu.getSelectedIndex() == 4)
        {
            jRadioButton1.setVisible(true);
            jRadioButton2.setVisible(true);
            jRadioButton3.setVisible(true);

            //menambahkan teks pada radio button
            jRadioButton1.setText("Reamur ke Kelvin");
            jRadioButton2.setText("Reamur ke Celcius");
            jRadioButton3.setText("Reamur ke Fahrenheit");
        }
    }//GEN-LAST:event_pilihsuhuActionPerformed

    private void btnexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMouseClicked
        // TODO add your handling code here:
        int X= JOptionPane.showConfirmDialog(null,"Keluar Aplikasi","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(X==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnexitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnBMI;
    private javax.swing.JLabel btnBentuk;
    private javax.swing.JLabel btnSains;
    private javax.swing.JLabel btnSuhu;
    private javax.swing.JLabel btnexit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel hasilkonversi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JPanel mnsuhu;
    private javax.swing.JComboBox<String> pilihsuhu;
    private javax.swing.JTextField valuesuhu;
    // End of variables declaration//GEN-END:variables
}
